### ISSUE TITLE
docker version does not work...

### ISSUE THREAD

**Issue by snufas** [SortAnon/ControllableTalkNet#22]
Hello getting the following errors when trying to run a docker container:

root@DESKTOP-7A6UGRU:/home/snufas/github_projects/docker_talknet# docker run -it --gpus all -p 8050:8050 talknet-offline
Updating TalkNet...
Updating HiFi-GAN...
Updating Python dependencies...
ERROR: pytorch-lightning 1.7.0 has requirement tensorboard>=2.9.1, but you'll have tensorboard 2.4.1 which is incompatible.
ERROR: pytorch-lightning 1.7.0 has requirement torch>=1.9.*, but you'll have torch 1.8.1+cu111 which is incompatible.
ERROR: pytorch-lightning 1.7.0 has requirement typing-extensions>=4.0.0, but you'll have typing-extensions 3.7.4.3 which is incompatible.
ERROR: tensorboard 2.9.1 has requirement protobuf<3.20,>=3.9.2, but you'll have protobuf 3.20.1 which is incompatible.
ERROR: pytorch-lightning 1.7.0 has requirement torch>=1.9.*, but you'll have torch 1.8.1+cu111 which is incompatible.
ERROR: pytorch-lightning 1.7.0 has requirement typing-extensions>=4.0.0, but you'll have typing-extensions 3.7.4.3 which is incompatible.
Launching TalkNet...
Traceback (most recent call last):
  File "talknet_offline.py", line 3, in <module>
    from controllable_talknet import *
  File "/talknet/controllable_talknet.py", line 3, in <module>
    import dash
  File "/usr/local/lib/python3.8/dist-packages/dash/__init__.py", line 5, in <module>
    from .dash import Dash, no_update  # noqa: F401,E402
  File "/usr/local/lib/python3.8/dist-packages/dash/dash.py", line 20, in <module>
    import flask
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 4, in <module>
    from . import json as json
  File "/usr/local/lib/python3.8/dist-packages/flask/json/__init__.py", line 8, in <module>
    from ..globals import current_app
  File "/usr/local/lib/python3.8/dist-packages/flask/globals.py", line 56, in <module>
    app_ctx: "AppContext" = LocalProxy(  # type: ignore[assignment]
TypeError: __init__() got an unexpected keyword argument 'unbound_message'

can you ubdate the dockerfile?
Thanks

**Comment by SortAnon** [comment]
Fixed. You shouldn't need to rebuild the image, just run it again.
